spring.application.name=homeVidya
spring.profiles.active=dev
# Shared JPA configuration
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# Server configuration
server.port=8080

# Springdoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.use-root-path=true

# Springdoc workaround for compatibility
springdoc.override-with-generic-response=false
